image: node:5.10.0

stages:
  - install_deps
  - build
#  - test
  - deploy_test
  - deploy_production
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
  - node_modules/
  - dist/

install_deps:
  stage: install_deps
  only:
  - develop
  - master
  script:
  - ls
  - echo "Restoring node_modules packages..."
  - npm install

#test:
#  stage: test
#  only:
#  - develop
#  - master
#  script:
#  - echo "Test running"
#  - npm run test

build:
  stage: build
  only:
  - develop
  - master
  script:
  - echo "Solution Debug Build..."
  - .\build\test\config.ps1
  - npm run build

deploy_test:
  stage: deploy_test
  only:
  - develop
  - master
  script:
  - echo "Deploy project to test server context..."
  - .\build\test\deploy.ps1

deploy_production:
  stage: deploy_production
  only:
  - develop
  - master
  script:
  - echo "Deploy project to production server context..."
  - .\build\production\config.ps1
  - npm run build
  - .\build\production\deploy.ps1